version: "3.8"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=ong
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql